// single clean script.js — no duplicated or nested blocks

const streams = {
  latest: document.getElementById("stream-latest"),
  founders: document.getElementById("stream-founders"),
  sectors: document.getElementById("stream-sectors"),
  spotlight: document.getElementById("stream-spotlight"),
};
const loading = document.getElementById("loading");
const overlay = document.getElementById("overlay");
const cardTemplate = document.getElementById("card-template");

const founders = [
  ["Aaliyah Chen", "Marcos Patel"],
  ["Dawn Everett", "Luis Romero"],
  ["Zoë Kim", "Fatima Sule"],
  ["Finn Gallagher", "Amir Rahman"],
  ["Nova Singh", "Jasper Cole"],
  ["Priya Das", "Theo Laurent"],
  ["Isaiah Moore", "Rin Ito"],
  ["Lena Bae", "Mateo Ortiz"],
  ["Suri Park", "Idris Okonkwo"],
  ["Anya Ivanova", "Leo Martins"],
];

const startups = [
  { name: "Voltline", tagline: "Realtime ops co-pilot for hardware startups", category: "Operations", description: "Voltline syncs factory telemetry with live war rooms so hardware founders can predict blockers before they hit production.", highlights: ["Seeded by Alloy Angels", "Trusted by 32 robotics teams"] },
  { name: "Beam", tagline: "Video-first sales showrooms for DTC founders", category: "Sales", description: "Beam turns every product drop into an immersive live studio with shoppable scenes, hosts, and real-time analytics.", highlights: ["Shopify integration", "Avg. conversion lift 24%"] },
  { name: "Halo", tagline: "No-code loyalty programs for consumer apps", category: "Marketing", description: "Halo lets product teams launch tiered rewards, streaks, and perks without writing a single line of code.", highlights: ["YC W23", "3M monthly active members"] },
  { name: "Orbit", tagline: "Community hub for pre-seed founders", category: "Community", description: "Orbit curates mastermind circles, async coaching, and capital intros tailored for the earliest-stage teams.", highlights: ["Global founder network", "Weekly investor office hours"] },
  { name: "Outlier", tagline: "AI briefs for product marketing teams", category: "AI", description: "Outlier generates on-brand launch briefs, positioning, and content calendars in seconds with human-in-the-loop controls.", highlights: ["SOC2 Type I", "Figma & Notion native"] },
  { name: "Signal", tagline: "Pulse checks across distributed startups", category: "Analytics", description: "Signal aggregates sentiment, roadmap risk, and retention health into a single dashboard for remote-first leadership teams.", highlights: ["Async-first", "Slack automations"] },
  { name: "Launchpad", tagline: "Embedded venture studio for creators", category: "Venture", description: "Launchpad helps breakout creators spin up product lines with fractional ops, funding, and shared GTM playbooks.", highlights: ["Backed by Night Ventures", "Creator revenue share"] },
  { name: "Neon Garden", tagline: "Hybrid events for the future of work", category: "Events", description: "Neon Garden designs pop-up HQs where distributed teams gather for launches, offsites, and investor showcases.", highlights: ["Carbon neutral", "Production in 12 cities"] },
  { name: "Afterglow", tagline: "Shopable livestream studios for founders", category: "Commerce", description: "Afterglow packages lighting, scripting, and commerce overlays so founders can host compelling drops from anywhere.", highlights: ["Creator agency partners", "Integrated fulfillment"] },
  { name: "Papertrail", tagline: "Automated data rooms for fundraising", category: "Finance", description: "Papertrail assembles diligence-ready data rooms with live metrics, stakeholder updates, and granular permissions.", highlights: ["SOC2 Type II", "One-click investor sync"] },
  { name: "Runway", tagline: "Hiring pods for breakout startups", category: "Talent", description: "Runway embeds curated talent partners who spin up full-stack hiring squads for the fastest growing companies.", highlights: ["NPS 82", "Avg. time-to-offer 21 days"] },
  { name: "Palette", tagline: "Brand identity kits generated by AI", category: "Design", description: "Palette crafts full brand identities, from logo to motion, using an AI engine trained on world-class creative direction.", highlights: ["Creative suite plugins", "HD export-ready"] },
  { name: "Synced", tagline: "Async collaboration feed for product squads", category: "Collaboration", description: "Synced keeps every decision, update, and handoff in a living feed built for teams who sprint across timezones.", highlights: ["Linear + Jira integrations", "Auto-summary digests"] },
  { name: "Zephyr", tagline: "Predictive insights for climate hardware", category: "Climate", description: "Zephyr models climate hardware performance and financing scenarios so teams can de-risk deployments pre-build.", highlights: ["Backed by Elemental", "DOE pilot ready"] },
  { name: "Alloy", tagline: "Modular manufacturing marketplace", category: "Industry", description: "Alloy connects product teams with modular manufacturing cells and instant capacity forecasting.", highlights: ["Global supplier grid", "Dynamic pricing"] },
  { name: "Prism", tagline: "Analytics for creator monetization", category: "Creator", description: "Prism visualizes conversion funnels, sponsorship revenue, and merch performance for modern creator businesses.", highlights: ["Cross-platform dashboards", "Auto payouts"] },
  { name: "Dash", tagline: "Decision OS for GTM teams", category: "SaaS", description: "Dash unifies forecasting, enablement, and deal support so revenue teams scale with clarity.", highlights: ["Enterprise ready", "AI pipeline coach"] },
  { name: "Skyline", tagline: "AI property intel for flexible offices", category: "Proptech", description: "Skyline scans global lease data and sentiment to pinpoint the best flexible office inventory for scaling teams.", highlights: ["Data refreshed hourly", "Preferred broker network"] },
  { name: "Driftspace", tagline: "Immersive demo environments for launches", category: "XR", description: "Driftspace spins up interactive demo worlds where launches and investor walkthroughs feel tactile and cinematic.", highlights: ["WebXR native", "Production partner suite"] },
  { name: "Relay", tagline: "Customer storytelling platform", category: "Marketing", description: "Relay packages customer stories into episodic drops with cinematic editing and distribution workflows.", highlights: ["Studios in LA & NYC", "Narrative strategy team"] },
  { name: "Cipher", tagline: "Security autopilot for modern startups", category: "Security", description: "Cipher hardens cloud infra with continuous monitoring, automated policy remediation, and human experts on call.", highlights: ["SOC2 automation", "PagerDuty escalation"] },
  { name: "Hyperion", tagline: "Revenue forecasting autopilot", category: "Finance", description: "Hyperion blends CRM, billing, and product telemetry into predictive revenue models for leadership teams.", highlights: ["Multi-scenario planning", "Dynamic board reports"] },
  { name: "Amplify", tagline: "Influencer deal flow CRM", category: "Influencer", description: "Amplify tracks creator relationships, sends offers, and automates payouts for brand collab teams.", highlights: ["30+ payment currencies", "Performance-based contracts"] },
  { name: "NovaDesk", tagline: "AI support agent for SaaS founders", category: "Support", description: "NovaDesk triages every ticket, drafts responses, and detects churn risk inside your help desk.", highlights: ["Zendesk & Intercom", "On-brand voice controls"] },
  { name: "Summit", tagline: "Comp planning for scaling teams", category: "HR", description: "Summit models comp scenarios across regions, equity bands, and growth plans so people teams stay ahead.", highlights: ["Equity refresh wizard", "HRIS sync"] },
  { name: "Momentum", tagline: "Investor update automation", category: "Productivity", description: "Momentum automates data pulls, narrative drafts, and stakeholder reminders for always-on investor comms.", highlights: ["GTM template library", "LP analytics"] },
  { name: "Vista", tagline: "Data layer for consumer insights", category: "Data", description: "Vista merges surveys, commerce, and social data into a single lens so brands know what to build next.", highlights: ["API-first", "Privacy built-in"] },
  { name: "Echo", tagline: "Audience testing for short form video", category: "Media", description: "Echo runs rapid-fire creative tests across TikTok, Shorts, and Reels with AI clips that self-optimize.", highlights: ["Creator network ready", "Auto A/B labeling"] },
  { name: "Flux", tagline: "DevOps autopilot for fast shipping", category: "DevTools", description: "Flux keeps deploys green with predictive alerts, rollback recipes, and AI fix suggestions for on-call teams.", highlights: ["Works with any CI", "Incident retros auto-drafted"] },
  { name: "Beacon", tagline: "Signals marketplace for emerging founders", category: "Community", description: "Beacon pairs scouts with founders through curated signal drops, live matches, and shared diligence notes.", highlights: ["Weekly deal flow drops", "Scouts in 14 cities"] }
];

const photoSet = [
  "https://images.unsplash.com/photo-1519455953755-af066f52f1ea?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1509098681029-b45e9c845022?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1471253784676-0f039a6aae4b?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=800&q=80",
];

let cursor = 0;
let totalRendered = 0;
const batchSize = 12;
let isLoading = false;

function createCard(data, seed) {
  const card = cardTemplate.content.firstElementChild.cloneNode(true);
  const media = card.querySelector(".card__media");
  const title = card.querySelector(".card__title");
  const category = card.querySelector(".card__category");
  const founderLine = card.querySelector(".card__founder");
  const tagline = card.querySelector(".card__tagline");
  const backTitle = card.querySelector(".card__back-title");
  const backCopy = card.querySelector(".card__back-copy");
  const highlightsList = card.querySelector(".card__highlights");
  const frontFace = card.querySelector(".card__face--front");
  const backFace = card.querySelector(".card__face--back");

  const photo = photoSet[seed % photoSet.length];
  media.style.backgroundImage = `url(${photo})`;

  title.textContent = data.name;
  category.textContent = data.category;
  tagline.textContent = data.tagline;

  const founderSet = founders[seed % founders.length];
  founderLine.textContent = founderSet.join(" · ");

  backTitle.textContent = data.name;
  backCopy.textContent = data.description;
  highlightsList.innerHTML = "";
  (data.highlights || []).forEach((highlight) => {
    const item = document.createElement("li");
    item.textContent = highlight;
    highlightsList.appendChild(item);
  });

  frontFace.setAttribute("aria-hidden", "false");
  backFace.setAttribute("aria-hidden", "true");

  function openCard() {
    card.classList.add("card--expanded", "card--flipped");
    frontFace.setAttribute("aria-hidden", "true");
    backFace.setAttribute("aria-hidden", "false");
    overlay && overlay.setAttribute("aria-hidden", "false");
    document.body.style.overflow = "hidden";
  }

  function closeCard() {
    card.classList.remove("card--expanded", "card--flipped");
    frontFace.setAttribute("aria-hidden", "false");
    backFace.setAttribute("aria-hidden", "true");
    overlay && overlay.setAttribute("aria-hidden", "true");
    document.body.style.overflow = "";
  }

  function handleActivate() {
    if (card.classList.contains("card--expanded")) {
      closeCard();
    } else {
      // Close any other open card first
      const open = document.querySelector(".card.card--expanded");
      if (open && open !== card) open.classList.remove("card--expanded", "card--flipped");
      openCard();
    }
  }

  card.addEventListener("click", handleActivate);
  const activatorKeys = ["Enter", " ", "Spacebar", "Space"];

  card.addEventListener("keydown", (event) => {
    if (activatorKeys.includes(event.key)) {
      event.preventDefault();
      handleActivate();
    }
  });

  // Overlay click/ESC to close
  if (overlay) {
    overlay.addEventListener("click", () => {
      if (card.classList.contains("card--expanded")) closeCard();
    });
    window.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && card.classList.contains("card--expanded")) closeCard();
    });
  }

  return card;
}

function getNextBatch() {
  const batch = [];
  for (let i = 0; i < batchSize; i++) {
    const idx = (cursor + i) % startups.length;
    batch.push({ ...startups[idx], id: cursor + i });
  }
  cursor += batchSize;
  return batch;
}

function renderBatch(targetEl, items) {
  if (!Array.isArray(items) || items.length === 0) return;
  const frag = document.createDocumentFragment();
  items.forEach((item, i) => {
    const card = createCard(item, totalRendered + i);
    frag.appendChild(card);
  });
  (targetEl || streams.latest).appendChild(frag);
  totalRendered += items.length;
}

function showLoading(show) {
  loading.setAttribute("aria-hidden", show ? "false" : "true");
}

async function loadMore() {
  if (isLoading) return;
  isLoading = true;
  showLoading(true);
  await new Promise((r) => setTimeout(r, 650));
  const batch = getNextBatch();
  renderBatch(streams.latest, batch);
  showLoading(false);
  isLoading = false;
}

function handleScroll() {
  const bottom = window.innerHeight + window.scrollY >= document.body.offsetHeight - 600;
  if (bottom) loadMore();
}

window.addEventListener("scroll", handleScroll, { passive: true });
window.addEventListener("resize", handleScroll);

(function init() {
  // Seed static sections
  renderBatch(streams.founders, getNextBatch());
  renderBatch(streams.sectors, getNextBatch());
  renderBatch(streams.spotlight, getNextBatch().slice(0, 6));
  // Seed latest feed
  renderBatch(streams.latest, getNextBatch());
  renderBatch(streams.latest, getNextBatch());
})();

